// <auto-generated />
namespace GroceryStoreManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MoveMaNCCfromMatHangtoPhieuNhap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoveMaNCCfromMatHangtoPhieuNhap));
        
        string IMigrationMetadata.Id
        {
            get { return "202012280247255_Move MaNCC from MatHang to PhieuNhap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
