// <auto-generated />
namespace GroceryStoreManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedgiabantoMaHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedgiabantoMaHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281213162_Added giaban to MaHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
